# -*- coding: utf-8 -*-
"""Image Generation (Hugging Face).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swk4vhVQltCf53GfPMV1OaWdhIAIEeqp
"""

import os

# Replace with your Hugging Face API token
os.environ["HUGGINGFACE_TOKEN"] = "YOUR_HUGGINGFACE_TOKEN"

from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
import matplotlib.pyplot as plt
import os

# Load Stable Diffusion pipeline from Hugging Face
model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_auth_token=os.environ["HUGGINGFACE_TOKEN"]
).to("cuda")  # use "cpu" if GPU not available

def generate_image(prompt, num_inference_steps=50, guidance_scale=7.5):
    """
    Generates an image from a text prompt using Stable Diffusion.

    Args:
        prompt (str): The text prompt to generate the image.
        num_inference_steps (int): Number of diffusion steps (more = higher quality).
        guidance_scale (float): How strongly the prompt is followed (higher = more faithful).

    Returns:
        PIL.Image: Generated image.
    """
    image = pipe(prompt, num_inference_steps=num_inference_steps, guidance_scale=guidance_scale).images[0]
    return image

# Example prompts
prompt1 = "A futuristic robot exploring outer space, digital art"
prompt2 = "A cozy cabin in a snowy forest, oil painting"

# Generate images
image1 = generate_image(prompt1)
image2 = generate_image(prompt2)

# Display images
plt.figure(figsize=(12,6))

plt.subplot(1,2,1)
plt.imshow(image1)
plt.axis("off")
plt.title("Robot in Space")

plt.subplot(1,2,2)
plt.imshow(image2)
plt.axis("off")
plt.title("Snowy Cabin")

plt.show()